# Platform
DEVICE_CODENAME := d2s
DEVICE_PATH := device/samsung/$(DEVICE_CODENAME)
BOARD_VENDOR := samsung
TARGET_BOARD_PLATFORM := exynos5
TARGET_BOARD_PLATFORM_GPU := mali-g76
TARGET_SOC := exynos9825
TARGET_BOOTLOADER_BOARD_NAME := universal9825
TARGET_NO_BOOTLOADER := true
TARGET_NO_RADIOIMAGE := true
TARGET_USES_UEFI := true

# Architecture
TARGET_ARCH := arm64
TARGET_ARCH_VARIANT := armv8-a
TARGET_CPU_ABI := arm64-v8a
TARGET_CPU_ABI2 :=
TARGET_CPU_VARIANT := generic
TARGET_CPU_VARIANT_RUNTIME := cortex-a75

# Secondary Architecture
TARGET_2ND_ARCH := arm
TARGET_2ND_ARCH_VARIANT := armv8-a
TARGET_2ND_CPU_ABI := armeabi-v7a
TARGET_2ND_CPU_ABI2 := armeabi
TARGET_2ND_CPU_VARIANT := generic
TARGET_2ND_CPU_VARIANT_RUNTIME := cortex-a55

# File systems
BOARD_HAS_LARGE_FILESYSTEM := true
TARGET_USERIMAGES_USE_EXT4 := true
TARGET_USERIMAGES_USE_F2FS := true
BOARD_HAS_NO_REAL_SDCARD := true
BOARD_BUILD_SYSTEM_ROOT_IMAGE := true

# TWRP specific build flags
RECOVERY_VARIANT := twrp
BOARD_VENDORIMAGE_FILE_SYSTEM_TYPE := ext4
TARGET_COPY_OUT_VENDOR := vendor
BOARD_SUPPRESS_SECURE_ERASE := true
TW_Y_OFFSET := 142
TW_H_OFFSET := -142
TW_THEME := portrait_hdpi
RECOVERY_SDCARD_ON_DATA := true
TARGET_RECOVERY_PIXEL_FORMAT := "ABGR_8888"
TW_BRIGHTNESS_PATH := "/sys/class/backlight/panel/brightness"
TW_MAX_BRIGHTNESS := 25500
TW_DEFAULT_BRIGHTNESS := 12800
TW_NO_REBOOT_BOOTLOADER := true
TW_HAS_DOWNLOAD_MODE := true
TW_INCLUDE_NTFS_3G := true
TW_EXCLUDE_SUPERSU := true
TW_EXTRA_LANGUAGES := true
TW_USE_NEW_MINADBD := true
TW_EXCLUDE_TWRPAPP := true
TW_EXCLUDE_DEFAULT_USB_INIT := true
TARGET_RECOVERY_FSTAB := $(DEVICE_PATH)/recovery.fstab
BOARD_RAMDISK_USE_LZMA := true

# Kernel
BOARD_KERNEL_BASE := 0x10000000
BOARD_KERNEL_PAGESIZE := 2048
BOARD_BOOT_HEADER_VERSION := 1
TARGET_KERNEL_SOURCE := kernel/samsung/universal9820
TARGET_KERNEL_CONFIG := exynos9820-d2s_defconfig
TARGET_KERNEL_ARCH := arm64
TARGET_KERNEL_CLANG_COMPILE := true
TARGET_KERNEL_CLANG_VERSION := r383902
BOARD_KERNEL_IMAGE_NAME := Image
NEED_KERNEL_MODULE_RECOVERY := true

# Samsung's kernel uses Android 11 platform macros independently of recovery.
TARGET_KERNEL_ADDITIONAL_FLAGS := PLATFORM_VERSION=11 ANDROID_MAJOR_VERSION=r HOSTCFLAGS="-fcommon -fuse-ld=lld"
# Resolve embedded firmware paths when Samsung's kernel is built out of tree.
TARGET_KERNEL_ADDITIONAL_FLAGS += KAFLAGS="-Wa,-I$(abspath $(TARGET_KERNEL_SOURCE))"
# Provide the cross-toolchain readelf required by Samsung's FIPS scripts.
D2S_KERNEL_TOOL_PATH := $(abspath $(DEVICE_PATH))/kernel-tools
D2S_KERNEL_TOOL_PATH := $(D2S_KERNEL_TOOL_PATH):$(abspath prebuilts/clang/host/linux-x86/clang-$(TARGET_KERNEL_CLANG_VERSION)/bin)
D2S_KERNEL_TOOL_PATH := $(D2S_KERNEL_TOOL_PATH):$(abspath prebuilts/gcc/linux-x86/aarch64/aarch64-linux-android-4.9/bin)
D2S_KERNEL_TOOL_PATH := $(D2S_KERNEL_TOOL_PATH):$(abspath prebuilts/gcc/linux-x86/arm/arm-linux-androideabi-4.9/bin)
D2S_KERNEL_TOOL_PATH := $(D2S_KERNEL_TOOL_PATH):$(abspath prebuilts/tools-lineage/linux-x86/bin)
TARGET_KERNEL_ADDITIONAL_FLAGS += PATH="$(D2S_KERNEL_TOOL_PATH):$(shell echo $$PATH)"

# Always build the kernel and DTBO from source.
override TARGET_PREBUILT_KERNEL :=
override TARGET_FORCE_PREBUILT_KERNEL :=
override OF_FORCE_PREBUILT_KERNEL := 0
BOARD_INCLUDE_RECOVERY_DTBO := true
BOARD_KERNEL_SEPARATED_DTBO := true
override BOARD_PREBUILT_DTBOIMAGE = $(TARGET_OUT_INTERMEDIATES)/DTBO_OBJ/arch/$(TARGET_KERNEL_ARCH)/boot/dtbo.img
override BOARD_PREBUILT_RECOVERY_DTBOIMAGE :=
BOARD_DTBO_CFG := $(DEVICE_PATH)/dtbo.cfg
BOARD_MKBOOTIMG_ARGS := --kernel_offset 0x00008000 --ramdisk_offset 0x01000000 --tags_offset 0x00000100 --header_version $(BOARD_BOOT_HEADER_VERSION)
